// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopUKW2025.DAL;

#nullable disable

namespace ShopUKW2025.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250310143621_data")]
    partial class data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopUKW2025.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Desc = "Filmy pełne akcji, napięcia i spektakularnych scen.",
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Desc = "Filmy mające na celu rozbawienie widza.",
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Desc = "Filmy koncentrujące się na emocjonalnych historiach.",
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Desc = "Filmy wywołujące strach i dreszczyk emocji.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Desc = "Filmy osadzone w przyszłości lub oparte na technologii.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 6,
                            Desc = "Filmy zawierające elementy magiczne lub nadprzyrodzone.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 7,
                            Desc = "Filmy skupiające się na relacjach miłosnych.",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 8,
                            Desc = "Filmy pełne napięcia i nieoczekiwanych zwrotów akcji.",
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryId = 9,
                            Desc = "Filmy animowane, przeznaczone zarówno dla dzieci, jak i dorosłych.",
                            Name = "Animation"
                        },
                        new
                        {
                            CategoryId = 10,
                            Desc = "Filmy przedstawiające rzeczywiste wydarzenia i tematy.",
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("ShopUKW2025.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Desc = "Akcja, która nie pozwala na moment odpoczynku.",
                            Director = "John McTiernan",
                            Price = 19.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 2,
                            Desc = "Komedia o przygodach grupy przyjaciół w Las Vegas.",
                            Director = "Todd Phillips",
                            Price = 14.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 3,
                            Desc = "Historia o nadziei i przyjaźni wśród więźniów.",
                            Director = "Frank Darabont",
                            Price = 12.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 4,
                            Desc = "Horror oparty na prawdziwych wydarzeniach, które przeraża.",
                            Director = "James Wan",
                            Price = 16.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 5,
                            Desc = "Film science-fiction o podróży przez przestrzeń i czas.",
                            Director = "Christopher Nolan",
                            Price = 21.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 6,
                            Desc = "Pierwsza część przygód młodego czarodzieja.",
                            Director = "Chris Columbus",
                            Price = 18.99m,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 7,
                            Desc = "Poruszająca historia miłości przez lata.",
                            Director = "Nick Cassavetes",
                            Price = 13.99m,
                            Title = "The Notebook"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 8,
                            Desc = "Thriller psychologiczny o włamaniu do snów.",
                            Director = "Christopher Nolan",
                            Price = 19.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 9,
                            Desc = "Animacja o przygodach zabawek, które ożywają.",
                            Director = "John Lasseter",
                            Price = 9.99m,
                            Title = "Toy Story"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 10,
                            Desc = "Dokument o życiu i pracy Freda Rogersa.",
                            Director = "Morgan Neville",
                            Price = 11.99m,
                            Title = "Won't You Be My Neighbor?"
                        });
                });

            modelBuilder.Entity("ShopUKW2025.Models.Film", b =>
                {
                    b.HasOne("ShopUKW2025.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopUKW2025.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
